version: '3'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - "80:80"
      - "443:443"
    links:
      - app:app.local
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/certs:/certs

  db:
    image: postgres
    # volumes:
    #   - ./docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortnr
    ports:
      - 5432:5432

  app:
    build: .
    working_dir: /srv/shortnr
    expose:
      - "3000"
      - "8080"
    volumes:
      - .:/srv/shortnr:rw
    links:
      - db:db.local
    depends_on:
      - db
