version: '3'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - "80:80"
      - "443:443"
    links:
      - app:app.local
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/certs:/certs

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6739'
    logging:
      driver: none

  app:
    build: .
    working_dir: /srv/shortnr
    expose:
      - "3000"
      - "8080"
    volumes:
      - .:/srv/shortnr:rw
    links:
      - redis:redis.local
    depends_on:
      - redis
