# This is an example configuration for a production ready shortnr

version: '3'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - "80:80"
      - "443:443"
    links:
      - shortnr:shortnr.local
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs

  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortnr
    ports:
      - 5432:5432
    logging:
      driver: none

  shortnr:
    image: pegase/shortnr
    environment:
      - NODE_CONFIG_DIR=/usr/local/shortnr
      - NODE_ENV=production
    expose:
      - "8765"
    volumes:
      - ./config:/usr/local/shortnr
    links:
      - db:db.local
    depends_on:
      - db
