# This is an example configuration for a production ready shortnr

version: '3'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - "80:80"
      - "443:443"
    links:
      - shortnr:shortnr.local
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6739'
    logging:
      driver: none

  shortnr:
    image: pegase/shortnr
    environment:
      - NODE_CONFIG_DIR=/usr/local/shortnr
      - NODE_ENV=production
    expose:
      - "8765"
    volumes:
      - ./config:/usr/local/shortnr
    links:
      - redis:redis.local
    depends_on:
      - redis
